### ISSUE TITLE
Create a Logo for auto-mail and update project with them 

### ISSUE THREAD

**Issue by muditrustagi** [muditrustagi/Auto-Mail#7]
Todo: 

 - Create a logo that depicts the ease or use that automail brings 
 - The logo should be white and blue (pallete, will be in comments)
 - The logo should have a touch of excel and mail like vibe
 - Add the logo to the macro-excel file and the readme file

**Comment by arathmus** [comment]
Logo File
![Screenshot 2022-10-09 at 11 31 33 PM](https://user-images.githubusercontent.com/115417911/194773297-766a52d6-20e6-4f3b-9bb4-ec79d79155d8.png)

**Comment by muditrustagi** [comment]
> Logo File ![Screenshot 2022-10-09 at 11 31 33 PM](https://user-images.githubusercontent.com/115417911/194773297-766a52d6-20e6-4f3b-9bb4-ec79d79155d8.png)

LGTM

**Comment by arathmus** [comment]
![rounded - logo](https://user-images.githubusercontent.com/115417911/194774223-29a8372c-7552-4303-a8e2-5998022287e9.png)
